/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AntecedentesRouteImport } from './routes/antecedentes'
import { Route as ContactoRouteImport } from './routes/contacto'
import { Route as FundacionRouteImport } from './routes/fundacion'
import { Route as KriyaYogaRouteImport } from './routes/kriya-yoga'
import { Route as LinajeRouteImport } from './routes/linaje'
import { Route as ProgramasRouteImport } from './routes/programas'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AntecedentesRoute = AntecedentesRouteImport.update({
  id: '/antecedentes',
  path: '/antecedentes',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactoRoute = ContactoRouteImport.update({
  id: '/contacto',
  path: '/contacto',
  getParentRoute: () => rootRouteImport,
} as any)
const FundacionRoute = FundacionRouteImport.update({
  id: '/fundacion',
  path: '/fundacion',
  getParentRoute: () => rootRouteImport,
} as any)
const KriyaYogaRoute = KriyaYogaRouteImport.update({
  id: '/kriya-yoga',
  path: '/kriya-yoga',
  getParentRoute: () => rootRouteImport,
} as any)
const LinajeRoute = LinajeRouteImport.update({
  id: '/linaje',
  path: '/linaje',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramasRoute = ProgramasRouteImport.update({
  id: '/programas',
  path: '/programas',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/antecedentes': typeof AntecedentesRoute
  '/contacto': typeof ContactoRoute
  '/fundacion': typeof FundacionRoute
  '/kriya-yoga': typeof KriyaYogaRoute
  '/linaje': typeof LinajeRoute
  '/programas': typeof ProgramasRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/antecedentes': typeof AntecedentesRoute
  '/contacto': typeof ContactoRoute
  '/fundacion': typeof FundacionRoute
  '/kriya-yoga': typeof KriyaYogaRoute
  '/linaje': typeof LinajeRoute
  '/programas': typeof ProgramasRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/antecedentes': typeof AntecedentesRoute
  '/contacto': typeof ContactoRoute
  '/fundacion': typeof FundacionRoute
  '/kriya-yoga': typeof KriyaYogaRoute
  '/linaje': typeof LinajeRoute
  '/programas': typeof ProgramasRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/antecedentes'
    | '/contacto'
    | '/fundacion'
    | '/kriya-yoga'
    | '/linaje'
    | '/programas'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/antecedentes'
    | '/contacto'
    | '/fundacion'
    | '/kriya-yoga'
    | '/linaje'
    | '/programas'
  id:
    | '__root__'
    | '/'
    | '/antecedentes'
    | '/contacto'
    | '/fundacion'
    | '/kriya-yoga'
    | '/linaje'
    | '/programas'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AntecedentesRoute: typeof AntecedentesRoute
  ContactoRoute: typeof ContactoRoute
  FundacionRoute: typeof FundacionRoute
  KriyaYogaRoute: typeof KriyaYogaRoute
  LinajeRoute: typeof LinajeRoute
  ProgramasRoute: typeof ProgramasRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/antecedentes': {
      id: '/antecedentes'
      path: '/antecedentes'
      fullPath: '/antecedentes'
      preLoaderRoute: typeof AntecedentesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacto': {
      id: '/contacto'
      path: '/contacto'
      fullPath: '/contacto'
      preLoaderRoute: typeof ContactoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fundacion': {
      id: '/fundacion'
      path: '/fundacion'
      fullPath: '/fundacion'
      preLoaderRoute: typeof FundacionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kriya-yoga': {
      id: '/kriya-yoga'
      path: '/kriya-yoga'
      fullPath: '/kriya-yoga'
      preLoaderRoute: typeof KriyaYogaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/linaje': {
      id: '/linaje'
      path: '/linaje'
      fullPath: '/linaje'
      preLoaderRoute: typeof LinajeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programas': {
      id: '/programas'
      path: '/programas'
      fullPath: '/programas'
      preLoaderRoute: typeof ProgramasRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AntecedentesRoute: AntecedentesRoute,
  ContactoRoute: ContactoRoute,
  FundacionRoute: FundacionRoute,
  KriyaYogaRoute: KriyaYogaRoute,
  LinajeRoute: LinajeRoute,
  ProgramasRoute: ProgramasRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
